/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as RegisterImport } from './routes/register'
import { Route as AuthImport } from './routes/_auth'
import { Route as AuthIndexImport } from './routes/_auth/index'
import { Route as AuthShoppingListIndexImport } from './routes/_auth/shopping-list/index'
import { Route as AuthShoppingListListIdIndexImport } from './routes/_auth/shopping-list/$listId/index'

// Create/Update Routes

const RegisterRoute = RegisterImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const AuthIndexRoute = AuthIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)

const AuthShoppingListIndexRoute = AuthShoppingListIndexImport.update({
  id: '/shopping-list/',
  path: '/shopping-list/',
  getParentRoute: () => AuthRoute,
} as any)

const AuthShoppingListListIdIndexRoute =
  AuthShoppingListListIdIndexImport.update({
    id: '/shopping-list/$listId/',
    path: '/shopping-list/$listId/',
    getParentRoute: () => AuthRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterImport
      parentRoute: typeof rootRoute
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexImport
      parentRoute: typeof AuthImport
    }
    '/_auth/shopping-list/': {
      id: '/_auth/shopping-list/'
      path: '/shopping-list'
      fullPath: '/shopping-list'
      preLoaderRoute: typeof AuthShoppingListIndexImport
      parentRoute: typeof AuthImport
    }
    '/_auth/shopping-list/$listId/': {
      id: '/_auth/shopping-list/$listId/'
      path: '/shopping-list/$listId'
      fullPath: '/shopping-list/$listId'
      preLoaderRoute: typeof AuthShoppingListListIdIndexImport
      parentRoute: typeof AuthImport
    }
  }
}

// Create and export the route tree

interface AuthRouteChildren {
  AuthIndexRoute: typeof AuthIndexRoute
  AuthShoppingListIndexRoute: typeof AuthShoppingListIndexRoute
  AuthShoppingListListIdIndexRoute: typeof AuthShoppingListListIdIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthIndexRoute: AuthIndexRoute,
  AuthShoppingListIndexRoute: AuthShoppingListIndexRoute,
  AuthShoppingListListIdIndexRoute: AuthShoppingListListIdIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof AuthRouteWithChildren
  '/register': typeof RegisterRoute
  '/': typeof AuthIndexRoute
  '/shopping-list': typeof AuthShoppingListIndexRoute
  '/shopping-list/$listId': typeof AuthShoppingListListIdIndexRoute
}

export interface FileRoutesByTo {
  '/register': typeof RegisterRoute
  '/': typeof AuthIndexRoute
  '/shopping-list': typeof AuthShoppingListIndexRoute
  '/shopping-list/$listId': typeof AuthShoppingListListIdIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_auth': typeof AuthRouteWithChildren
  '/register': typeof RegisterRoute
  '/_auth/': typeof AuthIndexRoute
  '/_auth/shopping-list/': typeof AuthShoppingListIndexRoute
  '/_auth/shopping-list/$listId/': typeof AuthShoppingListListIdIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/register'
    | '/'
    | '/shopping-list'
    | '/shopping-list/$listId'
  fileRoutesByTo: FileRoutesByTo
  to: '/register' | '/' | '/shopping-list' | '/shopping-list/$listId'
  id:
    | '__root__'
    | '/_auth'
    | '/register'
    | '/_auth/'
    | '/_auth/shopping-list/'
    | '/_auth/shopping-list/$listId/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  RegisterRoute: typeof RegisterRoute
}

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  RegisterRoute: RegisterRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_auth",
        "/register"
      ]
    },
    "/_auth": {
      "filePath": "_auth.tsx",
      "children": [
        "/_auth/",
        "/_auth/shopping-list/",
        "/_auth/shopping-list/$listId/"
      ]
    },
    "/register": {
      "filePath": "register.tsx"
    },
    "/_auth/": {
      "filePath": "_auth/index.tsx",
      "parent": "/_auth"
    },
    "/_auth/shopping-list/": {
      "filePath": "_auth/shopping-list/index.tsx",
      "parent": "/_auth"
    },
    "/_auth/shopping-list/$listId/": {
      "filePath": "_auth/shopping-list/$listId/index.tsx",
      "parent": "/_auth"
    }
  }
}
ROUTE_MANIFEST_END */
